#RGB配置
CONFIG_ZMK_RGB_UNDERGLOW=n
CONFIG_WS2812_STRIP=y
CONFIG_ZMK_RGB_UNDERGLOW_ON_START=n
CONFIG_ZMK_RGB_UNDERGLOW_BRT_START=60

#键盘进入空闲状态时关闭RGB
CONFIG_ZMK_BACKLIGHT_AUTO_OFF_IDLE=y
# Do not use the idle/wake cycle that re-enables RGB on key input.
CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_IDLE=n

# OLED配置
CONFIG_ZMK_DISPLAY=y
